
#include "nuitka/prelude.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_float_0_5;
PyObject *const_int_neg_1;
PyObject *const_int_neg_2;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_6;
PyObject *const_int_pos_7;
PyObject *const_int_pos_8;
PyObject *const_int_pos_9;
PyObject *const_str_chr_0;
PyObject *const_str_chr_1;
PyObject *const_str_chr_2;
PyObject *const_str_empty;
PyObject *const_str_space;
PyObject *const_dict_empty;
PyObject *const_int_pos_10;
PyObject *const_int_pos_11;
PyObject *const_int_pos_12;
PyObject *const_int_pos_13;
PyObject *const_int_pos_14;
PyObject *const_int_pos_15;
PyObject *const_int_pos_16;
PyObject *const_int_pos_17;
PyObject *const_int_pos_18;
PyObject *const_int_pos_19;
PyObject *const_int_pos_20;
PyObject *const_int_pos_21;
PyObject *const_int_pos_23;
PyObject *const_int_pos_24;
PyObject *const_int_pos_25;
PyObject *const_int_pos_28;
PyObject *const_int_pos_30;
PyObject *const_int_pos_32;
PyObject *const_int_pos_33;
PyObject *const_int_pos_40;
PyObject *const_int_pos_41;
PyObject *const_int_pos_50;
PyObject *const_int_pos_54;
PyObject *const_int_pos_56;
PyObject *const_int_pos_59;
PyObject *const_int_pos_62;
PyObject *const_str_chr_33;
PyObject *const_str_chr_34;
PyObject *const_str_chr_44;
PyObject *const_str_chr_60;
PyObject *const_str_chr_62;
PyObject *const_str_chr_91;
PyObject *const_str_chr_93;
PyObject *const_xrange_256;
PyObject *const_float_0_001;
PyObject *const_int_pos_100;
PyObject *const_int_pos_128;
PyObject *const_int_pos_180;
PyObject *const_int_pos_246;
PyObject *const_int_pos_250;
PyObject *const_int_pos_254;
PyObject *const_int_pos_255;
PyObject *const_int_pos_256;
PyObject *const_int_pos_257;
PyObject *const_int_pos_360;
PyObject *const_int_pos_512;
PyObject *const_str_newline;
PyObject *const_str_plain_1;
PyObject *const_str_plain_B;
PyObject *const_str_plain_H;
PyObject *const_str_plain_N;
PyObject *const_str_plain_R;
PyObject *const_str_plain_W;
PyObject *const_str_plain__;
PyObject *const_str_plain_a;
PyObject *const_str_plain_b;
PyObject *const_str_plain_c;
PyObject *const_str_plain_d;
PyObject *const_str_plain_e;
PyObject *const_str_plain_f;
PyObject *const_str_plain_h;
PyObject *const_str_plain_i;
PyObject *const_str_plain_j;
PyObject *const_str_plain_k;
PyObject *const_str_plain_l;
PyObject *const_str_plain_m;
PyObject *const_str_plain_n;
PyObject *const_str_plain_p;
PyObject *const_str_plain_q;
PyObject *const_str_plain_r;
PyObject *const_str_plain_s;
PyObject *const_str_plain_t;
PyObject *const_str_plain_u;
PyObject *const_str_plain_v;
PyObject *const_str_plain_w;
PyObject *const_str_plain_x;
PyObject *const_str_plain_y;
PyObject *const_str_plain_z;
PyObject *const_tuple_empty;
PyObject *const_int_pos_1000;
PyObject *const_str_plain_ID;
PyObject *const_str_plain_a1;
PyObject *const_str_plain_b0;
PyObject *const_str_plain_b1;
PyObject *const_str_plain_c1;
PyObject *const_str_plain_d0;
PyObject *const_str_plain_d1;
PyObject *const_str_plain_e1;
PyObject *const_str_plain_f1;
PyObject *const_str_plain_fp;
PyObject *const_str_plain_io;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_re;
PyObject *const_str_plain_x0;
PyObject *const_str_plain_x1;
PyObject *const_str_plain_x2;
PyObject *const_str_plain_x3;
PyObject *const_str_plain_y0;
PyObject *const_str_plain_y1;
PyObject *const_str_plain_y2;
PyObject *const_str_plain_y3;
PyObject *const_str_plain_INF;
PyObject *const_str_plain_KWD;
PyObject *const_str_plain_LIT;
PyObject *const_str_plain_abs;
PyObject *const_str_plain_add;
PyObject *const_str_plain_adv;
PyObject *const_str_plain_buf;
PyObject *const_str_plain_cid;
PyObject *const_str_plain_ctm;
PyObject *const_str_plain_def;
PyObject *const_str_plain_dic;
PyObject *const_str_plain_doc;
PyObject *const_str_plain_enc;
PyObject *const_str_plain_end;
PyObject *const_str_plain_get;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_map;
PyObject *const_str_plain_max;
PyObject *const_str_plain_min;
PyObject *const_str_plain_new;
PyObject *const_str_plain_obj;
PyObject *const_str_plain_out;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_pos;
PyObject *const_str_plain_pts;
PyObject *const_str_plain_run;
PyObject *const_str_plain_seq;
PyObject *const_str_plain_sub;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_tag;
PyObject *const_str_plain_zip;
PyObject *const_str_plain_CMap;
PyObject *const_str_plain_Kids;
PyObject *const_str_plain_Type;
PyObject *const_str_plain_args;
PyObject *const_str_plain_argv;
PyObject *const_str_plain_bbox;
PyObject *const_str_plain_bits;
PyObject *const_str_plain_char;
PyObject *const_str_plain_cmap;
PyObject *const_str_plain_code;
PyObject *const_str_plain_copy;
PyObject *const_str_plain_data;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_diff;
PyObject *const_str_plain_done;
PyObject *const_str_plain_fill;
PyObject *const_str_plain_find;
PyObject *const_str_plain_font;
PyObject *const_str_plain_func;
PyObject *const_str_plain_gray;
PyObject *const_str_plain_info;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_line;
PyObject *const_str_plain_long;
PyObject *const_str_plain_main;
PyObject *const_str_plain_mode;
PyObject *const_str_plain_name;
PyObject *const_str_plain_objs;
PyObject *const_str_plain_open;
PyObject *const_str_plain_pack;
PyObject *const_str_plain_page;
PyObject *const_str_plain_path;
PyObject *const_str_plain_pos0;
PyObject *const_str_plain_pred;
PyObject *const_str_plain_push;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_rise;
PyObject *const_str_plain_save;
PyObject *const_str_plain_seek;
PyObject *const_str_plain_self;
PyObject *const_str_plain_site;
PyObject *const_str_plain_size;
PyObject *const_str_plain_spec;
PyObject *const_str_plain_strm;
PyObject *const_str_plain_tell;
PyObject *const_str_plain_text;
PyObject *const_str_plain_type;
PyObject *const_str_plain_uniq;
PyObject *const_str_plain_xref;
PyObject *const_list_int_0_list;
PyObject *const_str_plain_Image;
PyObject *const_str_plain_PSEOF;
PyObject *const_str_plain_Plane;
PyObject *const_str_plain_Width;
PyObject *const_str_plain__objs;
PyObject *const_str_plain_array;
PyObject *const_str_plain_attrs;
PyObject *const_str_plain_begin;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_close;
PyObject *const_str_plain_codec;
PyObject *const_str_plain_csort;
PyObject *const_str_plain_debug;
PyObject *const_str_plain_flush;
PyObject *const_str_plain_fname;
PyObject *const_str_plain_genno;
PyObject *const_str_plain_group;
PyObject *const_str_plain_image;
PyObject *const_str_plain_index;
PyObject *const_str_plain_klass;
PyObject *const_str_plain_level;
PyObject *const_str_plain_match;
PyObject *const_str_plain_names;
PyObject *const_str_plain_objid;
PyObject *const_str_plain_outfp;
PyObject *const_str_plain_props;
PyObject *const_str_plain_range;
PyObject *const_str_plain_reset;
PyObject *const_str_plain_scale;
PyObject *const_str_plain_split;
PyObject *const_str_plain_start;
PyObject *const_str_plain_token;
PyObject *const_str_plain_utils;
PyObject *const_str_plain_width;
PyObject *const_str_plain_write;
PyObject *const_str_plain_xrefs;
PyObject *const_str_angle_lambda;
PyObject *const_str_plain_BUFSIZ;
PyObject *const_str_plain_CMapDB;
PyObject *const_str_plain_Filter;
PyObject *const_str_plain_Height;
PyObject *const_str_plain_LTChar;
PyObject *const_str_plain_LTLine;
PyObject *const_str_plain_LTPage;
PyObject *const_str_plain_LTRect;
PyObject *const_str_plain_LTText;
PyObject *const_str_plain_Length;
PyObject *const_str_plain_STRICT;
PyObject *const_str_plain__stack;
PyObject *const_str_plain_append;
PyObject *const_str_plain_bufpos;
PyObject *const_str_plain_cmapdb;
PyObject *const_str_plain_colors;
PyObject *const_str_plain_decode;
PyObject *const_str_plain_do_tag;
PyObject *const_str_plain_encode;
PyObject *const_str_plain_exists;
PyObject *const_str_plain_extend;
PyObject *const_str_plain_format;
PyObject *const_str_plain_fsplit;
PyObject *const_str_plain_getobj;
PyObject *const_str_plain_groups;
PyObject *const_str_plain_height;
PyObject *const_str_plain_ignore;
PyObject *const_str_plain_length;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_matrix;
PyObject *const_str_plain_normal;
PyObject *const_str_plain_offset;
PyObject *const_str_plain_pageid;
PyObject *const_str_plain_pageno;
PyObject *const_str_plain_params;
PyObject *const_str_plain_parser;
PyObject *const_str_plain_popall;
PyObject *const_str_plain_remove;
PyObject *const_str_plain_render;
PyObject *const_str_plain_result;
PyObject *const_str_plain_rotate;
PyObject *const_str_plain_search;
PyObject *const_str_plain_sorted;
PyObject *const_str_plain_stdout;
PyObject *const_str_plain_stream;
PyObject *const_str_plain_stroke;
PyObject *const_str_plain_struct;
PyObject *const_str_plain_unichr;
PyObject *const_str_plain_unpack;
PyObject *const_str_plain_update;
PyObject *const_str_plain_xrange;
PyObject *const_tuple_none_tuple;
PyObject *const_str_angle_genexpr;
PyObject *const_str_plain_BytesIO;
PyObject *const_str_plain_Columns;
PyObject *const_str_plain_LTCurve;
PyObject *const_str_plain_LTImage;
PyObject *const_str_plain_PDFPage;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___len__;
PyObject *const_str_plain_analyze;
PyObject *const_str_plain_caching;
PyObject *const_str_plain_catalog;
PyObject *const_str_plain_charpos;
PyObject *const_str_plain_columns;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_decrypt;
PyObject *const_str_plain_default;
PyObject *const_str_plain_dirname;
PyObject *const_str_plain_encrypt;
PyObject *const_str_plain_end_tag;
PyObject *const_str_plain_environ;
PyObject *const_str_plain_evenodd;
PyObject *const_str_plain_fillbuf;
PyObject *const_str_plain_filters;
PyObject *const_str_plain_get_any;
PyObject *const_str_plain_get_pts;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_leading;
PyObject *const_str_plain_linepos;
PyObject *const_str_plain_logging;
PyObject *const_str_plain_nunpack;
PyObject *const_str_plain_offsets;
PyObject *const_str_plain_pdffont;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_rsrcmgr;
PyObject *const_str_plain_scaling;
PyObject *const_str_plain_set_ctm;
PyObject *const_str_plain_srcsize;
PyObject *const_tuple_false_tuple;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_plain_ENCODING;
PyObject *const_str_plain_Encoding;
PyObject *const_str_plain_LAParams;
PyObject *const_str_plain_LTFigure;
PyObject *const_str_plain_PSObject;
PyObject *const_str_plain_TestCase;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___repr__;
PyObject *const_str_plain_bbox2str;
PyObject *const_str_plain_choplist;
PyObject *const_str_plain_contents;
PyObject *const_str_plain_decipher;
PyObject *const_str_plain_end_page;
PyObject *const_str_plain_end_type;
PyObject *const_str_plain_exc_type;
PyObject *const_str_plain_fallback;
PyObject *const_str_plain_fontname;
PyObject *const_str_plain_fontsize;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_get_cmap;
PyObject *const_str_plain_get_data;
PyObject *const_str_plain_get_text;
PyObject *const_str_plain_isnumber;
PyObject *const_str_plain_laparams;
PyObject *const_str_plain_maxpages;
PyObject *const_str_plain_mediabox;
PyObject *const_str_plain_nextline;
PyObject *const_str_plain_password;
PyObject *const_str_plain_pdfcolor;
PyObject *const_str_plain_pdftypes;
PyObject *const_str_plain_psparser;
PyObject *const_str_plain_resolve1;
PyObject *const_str_plain_rldecode;
PyObject *const_str_plain_unittest;
PyObject *const_str_plain_vertical;
PyObject *const_str_plain_LTTextBox;
PyObject *const_str_plain_PDFDevice;
PyObject *const_str_plain_PDFObjRef;
PyObject *const_str_plain_PDFParser;
PyObject *const_str_plain_PDFStream;
PyObject *const_str_plain_PSKeyword;
PyObject *const_str_plain_PSLiteral;
PyObject *const_str_plain_Resources;
PyObject *const_str_plain_ToUnicode;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain_all_texts;
PyObject *const_str_plain_begin_tag;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_char_disp;
PyObject *const_str_plain_charspace;
PyObject *const_str_plain_exc_value;
PyObject *const_str_plain_get_bound;
PyObject *const_str_plain_get_pages;
PyObject *const_str_plain_get_width;
PyObject *const_str_plain_int_value;
PyObject *const_str_plain_iteritems;
PyObject *const_str_plain_linewidth;
PyObject *const_str_plain_lzwdecode;
PyObject *const_str_plain_nexttoken;
PyObject *const_str_plain_num_value;
PyObject *const_str_plain_pdfparser;
PyObject *const_str_plain_resources;
PyObject *const_str_plain_set_objid;
PyObject *const_str_plain_startxref;
PyObject *const_str_plain_str_value;
PyObject *const_str_plain_textstate;
PyObject *const_str_plain_to_unichr;
PyObject *const_str_plain_wordspace;
PyObject *const_str_plain_CMapParser;
PyObject *const_str_plain_ColorSpace;
PyObject *const_str_plain_EncodingDB;
PyObject *const_str_plain_LTTextLine;
PyObject *const_str_plain_PDFCIDFont;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain_begin_page;
PyObject *const_str_plain_boxes_flow;
PyObject *const_str_plain_char_width;
PyObject *const_str_plain_colorspace;
PyObject *const_str_plain_dict_value;
PyObject *const_str_plain_do_keyword;
PyObject *const_str_plain_encodingdb;
PyObject *const_str_plain_end_figure;
PyObject *const_str_plain_get_height;
PyObject *const_str_plain_get_objids;
PyObject *const_str_plain_get_unichr;
PyObject *const_str_plain_layoutmode;
PyObject *const_str_plain_linematrix;
PyObject *const_str_plain_list_value;
PyObject *const_str_plain_matrix2str;
PyObject *const_str_plain_nextobject;
PyObject *const_str_plain_paint_path;
PyObject *const_str_plain_start_type;
PyObject *const_str_plain_startswith;
PyObject *const_str_plain_ImageWriter;
PyObject *const_str_plain_KEYWORD_DEF;
PyObject *const_str_plain_KEYWORD_OBJ;
PyObject *const_str_plain_LTContainer;
PyObject *const_str_plain_LTTextGroup;
PyObject *const_str_plain_PDFDocument;
PyObject *const_str_plain_PSException;
PyObject *const_str_plain_PSTypeError;
PyObject *const_str_plain___delattr__;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___setattr__;
PyObject *const_str_plain_add_results;
PyObject *const_str_plain_assertEqual;
PyObject *const_str_plain_char_margin;
PyObject *const_str_plain_cid2unicode;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_decode_text;
PyObject *const_str_plain_get_descent;
PyObject *const_str_plain_get_filters;
PyObject *const_str_plain_get_rawdata;
PyObject *const_str_plain_imagewriter;
PyObject *const_str_plain_is_vertical;
PyObject *const_str_plain_line_margin;
PyObject *const_str_plain_mult_matrix;
PyObject *const_str_plain_ncomponents;
PyObject *const_str_plain_render_char;
PyObject *const_str_plain_word_margin;
PyObject *const_tuple_int_neg_1_tuple;
PyObject *const_tuple_int_pos_1_tuple;
PyObject *const_tuple_int_pos_2_tuple;
PyObject *const_tuple_int_pos_3_tuple;
PyObject *const_tuple_int_pos_4_tuple;
PyObject *const_tuple_str_space_tuple;
PyObject *const_str_plain_CMapNotFound;
PyObject *const_str_plain_FONT_METRICS;
PyObject *const_str_plain_KEYWORD_XREF;
PyObject *const_str_plain_PDFException;
PyObject *const_str_plain_PDFFontError;
PyObject *const_str_plain_PDFType1Font;
PyObject *const_str_plain_PDFType3Font;
PyObject *const_str_plain_PDFTypeError;
PyObject *const_str_plain_TagExtractor;
PyObject *const_str_plain_XMLConverter;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___contains__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain_begin_figure;
PyObject *const_str_plain_decipher_all;
PyObject *const_str_plain_export_image;
PyObject *const_str_plain_get_encoding;
PyObject *const_str_plain_graphicstate;
PyObject *const_str_plain_is_multibyte;
PyObject *const_str_plain_keyword_name;
PyObject *const_str_plain_literal_name;
PyObject *const_str_plain_name2unicode;
PyObject *const_str_plain_process_page;
PyObject *const_str_plain_render_image;
PyObject *const_str_plain_revreadlines;
PyObject *const_str_plain_set_document;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_stream_value;
PyObject *const_str_plain_stripcontrol;
PyObject *const_str_plain_HTMLConverter;
PyObject *const_str_plain_PDFColorSpace;
PyObject *const_str_plain_PDFTextDevice;
PyObject *const_str_plain_PSStackParser;
PyObject *const_str_plain_PSSyntaxError;
PyObject *const_str_plain_TextConverter;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain_ascii85decode;
PyObject *const_str_plain_exc_traceback;
PyObject *const_str_plain_render_string;
PyObject *const_tuple_int_0_int_0_tuple;
PyObject *const_tuple_str_newline_tuple;
PyObject *const_tuple_str_plain_x_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_FileUnicodeMap;
PyObject *const_str_plain_PDFDocEncoding;
PyObject *const_str_plain_PDFSyntaxError;
PyObject *const_str_plain_add_cid2unichr;
PyObject *const_str_plain_asciihexdecode;
PyObject *const_str_plain_ccittfaxdecode;
PyObject *const_str_plain_is_extractable;
PyObject *const_str_plain_MATRIX_IDENTITY;
PyObject *const_str_plain_PDFStreamParser;
PyObject *const_str_plain_PDFTrueTypeFont;
PyObject *const_str_plain_apply_matrix_pt;
PyObject *const_str_plain_detect_vertical;
PyObject *const_str_plain_get_unicode_map;
PyObject *const_tuple_str_plain_KWD_tuple;
PyObject *const_tuple_str_plain_LIT_tuple;
PyObject *const_tuple_str_plain_def_tuple;
PyObject *const_tuple_str_plain_enc_tuple;
PyObject *const_tuple_str_plain_end_tuple;
PyObject *const_tuple_str_plain_obj_tuple;
PyObject *const_str_plain_BitsPerComponent;
PyObject *const_str_plain_StandardEncoding;
PyObject *const_str_plain_bitspercomponent;
PyObject *const_str_plain_get_writing_mode;
PyObject *const_str_plain_translate_matrix;
PyObject *const_tuple_str_plain_CMap_tuple;
PyObject *const_tuple_str_plain_Type_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain_LTTextBoxVertical;
PyObject *const_str_plain_PDFObjectNotFound;
PyObject *const_str_plain_apply_matrix_norm;
PyObject *const_str_plain_check_extractable;
PyObject *const_str_plain_glyphname2unicode;
PyObject *const_tuple_str_plain_Image_tuple;
PyObject *const_tuple_str_plain_PSEOF_tuple;
PyObject *const_tuple_str_plain_begin_tuple;
PyObject *const_str_plain_LITERAL_DEVICE_RGB;
PyObject *const_str_plain_PDFPageInterpreter;
PyObject *const_str_plain_PDFResourceManager;
PyObject *const_tuple_str_plain_CMapDB_tuple;
PyObject *const_tuple_str_plain_STRICT_tuple;
PyObject *const_str_plain_LITERALS_DCT_DECODE;
PyObject *const_str_plain_LITERAL_DEVICE_CMYK;
PyObject *const_str_plain_LITERAL_DEVICE_GRAY;
PyObject *const_str_plain_apply_png_predictor;
PyObject *const_tuple_str_plain_BytesIO_tuple;
PyObject *const_tuple_str_plain_nunpack_tuple;
PyObject *const_str_plain_PDFUnicodeNotDefined;
PyObject *const_tuple_str_plain_bbox2str_tuple;
PyObject *const_tuple_str_plain_choplist_tuple;
PyObject *const_tuple_str_plain_isnumber_tuple;
PyObject *const_tuple_str_plain_resolve1_tuple;
PyObject *const_str_plain_PREDEFINED_COLORSPACE;
PyObject *const_tuple_int_pos_1_int_pos_1_tuple;
PyObject *const_tuple_str_plain_PDFObjRef_tuple;
PyObject *const_tuple_str_plain_PDFParser_tuple;
PyObject *const_tuple_str_plain_PDFStream_tuple;
PyObject *const_tuple_str_plain_PSLiteral_tuple;
PyObject *const_tuple_str_plain_int_value_tuple;
PyObject *const_tuple_str_plain_dict_value_tuple;
PyObject *const_tuple_str_plain_list_value_tuple;
PyObject *const_tuple_str_plain_PDFDocument_tuple;
PyObject *const_tuple_str_plain_mult_matrix_tuple;
PyObject *const_tuple_str_plain_PDFException_tuple;
PyObject *const_tuple_str_plain_literal_name_tuple;
PyObject *const_tuple_str_plain_name2unicode_tuple;
PyObject *const_tuple_str_plain_stream_value_tuple;
PyObject *const_tuple_str_plain_PSStackParser_tuple;
PyObject *const_tuple_str_plain_PSSyntaxError_tuple;
PyObject *const_str_plain_PDFTextExtractionNotAllowed;
PyObject *const_tuple_str_plain_apply_matrix_pt_tuple;
PyObject *const_tuple_str_plain_self_str_plain_i_tuple;
PyObject *const_tuple_str_plain_self_str_plain_n_tuple;
PyObject *const_tuple_str_plain_self_str_plain_s_tuple;
PyObject *const_tuple_str_plain_PDFObjectNotFound_tuple;
PyObject *const_tuple_str_plain_self_str_plain_fp_tuple;
PyObject *const_tuple_str_plain_self_str_plain_cid_tuple;
PyObject *const_tuple_str_plain_self_str_plain_ctm_tuple;
PyObject *const_tuple_str_plain_self_str_plain_obj_tuple;
PyObject *const_tuple_str_plain_self_str_plain_pos_tuple;
PyObject *const_tuple_str_plain_self_str_plain_tag_tuple;
PyObject *const_tuple_str_plain_self_str_plain_data_tuple;
PyObject *const_tuple_str_plain_self_str_plain_name_tuple;
PyObject *const_tuple_str_plain_self_str_plain_objs_tuple;
PyObject *const_tuple_str_plain_self_str_plain_page_tuple;
PyObject *const_tuple_str_plain_self_str_plain_text_tuple;
PyObject *const_tuple_str_plain_PDFUnicodeNotDefined_tuple;
PyObject *const_str_digest_00b407740d742ef21d6f97842b0811ea;
PyObject *const_str_digest_06b582bb8a7d7354812dca18aef147d5;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_4b5c38a441de1271115ffc49566d0c91;
PyObject *const_str_digest_4d088de100fe5354b20a010ce1db7f29;
PyObject *const_str_digest_58961c73026e70b23b08cf381b49e04e;
PyObject *const_str_digest_5bc6acbbb9e0adb8dabbc1a8cf202f2d;
PyObject *const_str_digest_5cf0452130fc4fd9d925cac8f015f9d1;
PyObject *const_str_digest_6d86adbb5b668bab4cd670281ea4b3e0;
PyObject *const_str_digest_7532b9d7f11d8fedcf0f9e47d9f9d1da;
PyObject *const_str_digest_7bb187c562694df4ba2daaaf74308c83;
PyObject *const_str_digest_89cffbfc3ef10076664cbfd1fe7e6033;
PyObject *const_str_digest_8e5335fb02f73f9b285b14387631d654;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_a5f56e291553139a63a10626179e7804;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_b3b014cceb34671e9d2eebc9b6361b5c;
PyObject *const_str_digest_b9c4baf879ebd882d40843df3a4dead7;
PyObject *const_str_digest_c075052d723d6707083e869a0e3659bb;
PyObject *const_str_digest_d1e9155136963092d9fab9b67fbb0f7f;
PyObject *const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77;
PyObject *const_str_digest_e399ba4554180f37de594a6743234f17;
PyObject *const_str_digest_f454f8d0bf3383d8495a04e69ba795a3;
PyObject *const_str_digest_f6a581251841acee771bacb236f706e6;
PyObject *const_str_digest_fa91b370bf4aa8601b20ad022c04c7f5;
PyObject *const_tuple_9610428a1ba6846a8d44a05bfd7779c2_tuple;
PyObject *const_tuple_b0c00933e83a0151953f3a00c2178204_tuple;
PyObject *const_tuple_str_digest_00b407740d742ef21d6f97842b0811ea_tuple;
PyObject *const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple;
PyObject *const_tuple_str_digest_fa91b370bf4aa8601b20ad022c04c7f5_tuple;
PyObject *const_tuple_str_plain_self_str_plain_objs_str_plain_obj_tuple;
PyObject *const_tuple_str_plain_self_str_plain_tag_str_plain_props_tuple;
PyObject *const_tuple_str_plain_self_str_plain_name_str_plain_stream_tuple;
PyObject *const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_x_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyInt_FromLong( 0l );
    const_str_dot = UNSTREAM_CHAR( 46, 0 );
    const_float_0_5 = UNSTREAM_FLOAT( &constant_bin[ 198176 ] );
    const_int_neg_1 = PyInt_FromLong( -1l );
    const_int_neg_2 = PyInt_FromLong( -2l );
    const_int_pos_1 = PyInt_FromLong( 1l );
    const_int_pos_2 = PyInt_FromLong( 2l );
    const_int_pos_3 = PyInt_FromLong( 3l );
    const_int_pos_4 = PyInt_FromLong( 4l );
    const_int_pos_5 = PyInt_FromLong( 5l );
    const_int_pos_6 = PyInt_FromLong( 6l );
    const_int_pos_7 = PyInt_FromLong( 7l );
    const_int_pos_8 = PyInt_FromLong( 8l );
    const_int_pos_9 = PyInt_FromLong( 9l );
    const_str_chr_0 = UNSTREAM_CHAR( 0, 0 );
    const_str_chr_1 = UNSTREAM_CHAR( 1, 0 );
    const_str_chr_2 = UNSTREAM_CHAR( 2, 0 );
    const_str_empty = UNSTREAM_STRING( &constant_bin[ 0 ], 0, 0 );
    const_str_space = UNSTREAM_CHAR( 32, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_int_pos_10 = PyInt_FromLong( 10l );
    const_int_pos_11 = PyInt_FromLong( 11l );
    const_int_pos_12 = PyInt_FromLong( 12l );
    const_int_pos_13 = PyInt_FromLong( 13l );
    const_int_pos_14 = PyInt_FromLong( 14l );
    const_int_pos_15 = PyInt_FromLong( 15l );
    const_int_pos_16 = PyInt_FromLong( 16l );
    const_int_pos_17 = PyInt_FromLong( 17l );
    const_int_pos_18 = PyInt_FromLong( 18l );
    const_int_pos_19 = PyInt_FromLong( 19l );
    const_int_pos_20 = PyInt_FromLong( 20l );
    const_int_pos_21 = PyInt_FromLong( 21l );
    const_int_pos_23 = PyInt_FromLong( 23l );
    const_int_pos_24 = PyInt_FromLong( 24l );
    const_int_pos_25 = PyInt_FromLong( 25l );
    const_int_pos_28 = PyInt_FromLong( 28l );
    const_int_pos_30 = PyInt_FromLong( 30l );
    const_int_pos_32 = PyInt_FromLong( 32l );
    const_int_pos_33 = PyInt_FromLong( 33l );
    const_int_pos_40 = PyInt_FromLong( 40l );
    const_int_pos_41 = PyInt_FromLong( 41l );
    const_int_pos_50 = PyInt_FromLong( 50l );
    const_int_pos_54 = PyInt_FromLong( 54l );
    const_int_pos_56 = PyInt_FromLong( 56l );
    const_int_pos_59 = PyInt_FromLong( 59l );
    const_int_pos_62 = PyInt_FromLong( 62l );
    const_str_chr_33 = UNSTREAM_CHAR( 33, 0 );
    const_str_chr_34 = UNSTREAM_CHAR( 34, 0 );
    const_str_chr_44 = UNSTREAM_CHAR( 44, 0 );
    const_str_chr_60 = UNSTREAM_CHAR( 60, 0 );
    const_str_chr_62 = UNSTREAM_CHAR( 62, 0 );
    const_str_chr_91 = UNSTREAM_CHAR( 91, 0 );
    const_str_chr_93 = UNSTREAM_CHAR( 93, 0 );
    const_xrange_256 = MAKE_XRANGE( 0, 256, 1 );
    const_float_0_001 = UNSTREAM_FLOAT( &constant_bin[ 198184 ] );
    const_int_pos_100 = PyInt_FromLong( 100l );
    const_int_pos_128 = PyInt_FromLong( 128l );
    const_int_pos_180 = PyInt_FromLong( 180l );
    const_int_pos_246 = PyInt_FromLong( 246l );
    const_int_pos_250 = PyInt_FromLong( 250l );
    const_int_pos_254 = PyInt_FromLong( 254l );
    const_int_pos_255 = PyInt_FromLong( 255l );
    const_int_pos_256 = PyInt_FromLong( 256l );
    const_int_pos_257 = PyInt_FromLong( 257l );
    const_int_pos_360 = PyInt_FromLong( 360l );
    const_int_pos_512 = PyInt_FromLong( 512l );
    const_str_newline = UNSTREAM_CHAR( 10, 0 );
    const_str_plain_1 = UNSTREAM_CHAR( 49, 0 );
    const_str_plain_B = UNSTREAM_CHAR( 66, 1 );
    const_str_plain_H = UNSTREAM_CHAR( 72, 1 );
    const_str_plain_N = UNSTREAM_CHAR( 78, 1 );
    const_str_plain_R = UNSTREAM_CHAR( 82, 1 );
    const_str_plain_W = UNSTREAM_CHAR( 87, 1 );
    const_str_plain__ = UNSTREAM_CHAR( 95, 1 );
    const_str_plain_a = UNSTREAM_CHAR( 97, 1 );
    const_str_plain_b = UNSTREAM_CHAR( 98, 1 );
    const_str_plain_c = UNSTREAM_CHAR( 99, 1 );
    const_str_plain_d = UNSTREAM_CHAR( 100, 1 );
    const_str_plain_e = UNSTREAM_CHAR( 101, 1 );
    const_str_plain_f = UNSTREAM_CHAR( 102, 1 );
    const_str_plain_h = UNSTREAM_CHAR( 104, 1 );
    const_str_plain_i = UNSTREAM_CHAR( 105, 1 );
    const_str_plain_j = UNSTREAM_CHAR( 106, 1 );
    const_str_plain_k = UNSTREAM_CHAR( 107, 1 );
    const_str_plain_l = UNSTREAM_CHAR( 108, 1 );
    const_str_plain_m = UNSTREAM_CHAR( 109, 1 );
    const_str_plain_n = UNSTREAM_CHAR( 110, 1 );
    const_str_plain_p = UNSTREAM_CHAR( 112, 1 );
    const_str_plain_q = UNSTREAM_CHAR( 113, 1 );
    const_str_plain_r = UNSTREAM_CHAR( 114, 1 );
    const_str_plain_s = UNSTREAM_CHAR( 115, 1 );
    const_str_plain_t = UNSTREAM_CHAR( 116, 1 );
    const_str_plain_u = UNSTREAM_CHAR( 117, 1 );
    const_str_plain_v = UNSTREAM_CHAR( 118, 1 );
    const_str_plain_w = UNSTREAM_CHAR( 119, 1 );
    const_str_plain_x = UNSTREAM_CHAR( 120, 1 );
    const_str_plain_y = UNSTREAM_CHAR( 121, 1 );
    const_str_plain_z = UNSTREAM_CHAR( 122, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_int_pos_1000 = PyInt_FromLong( 1000l );
    const_str_plain_ID = UNSTREAM_STRING( &constant_bin[ 4770 ], 2, 1 );
    const_str_plain_a1 = UNSTREAM_STRING( &constant_bin[ 68099 ], 2, 1 );
    const_str_plain_b0 = UNSTREAM_STRING( &constant_bin[ 198192 ], 2, 1 );
    const_str_plain_b1 = UNSTREAM_STRING( &constant_bin[ 3260 ], 2, 1 );
    const_str_plain_c1 = UNSTREAM_STRING( &constant_bin[ 198194 ], 2, 1 );
    const_str_plain_d0 = UNSTREAM_STRING( &constant_bin[ 3669 ], 2, 1 );
    const_str_plain_d1 = UNSTREAM_STRING( &constant_bin[ 176208 ], 2, 1 );
    const_str_plain_e1 = UNSTREAM_STRING( &constant_bin[ 4439 ], 2, 1 );
    const_str_plain_f1 = UNSTREAM_STRING( &constant_bin[ 198196 ], 2, 1 );
    const_str_plain_fp = UNSTREAM_STRING( &constant_bin[ 334 ], 2, 1 );
    const_str_plain_io = UNSTREAM_STRING( &constant_bin[ 196 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING( &constant_bin[ 131 ], 2, 1 );
    const_str_plain_rb = UNSTREAM_STRING( &constant_bin[ 5502 ], 2, 1 );
    const_str_plain_re = UNSTREAM_STRING( &constant_bin[ 375 ], 2, 1 );
    const_str_plain_x0 = UNSTREAM_STRING( &constant_bin[ 4035 ], 2, 1 );
    const_str_plain_x1 = UNSTREAM_STRING( &constant_bin[ 7178 ], 2, 1 );
    const_str_plain_x2 = UNSTREAM_STRING( &constant_bin[ 198198 ], 2, 1 );
    const_str_plain_x3 = UNSTREAM_STRING( &constant_bin[ 198200 ], 2, 1 );
    const_str_plain_y0 = UNSTREAM_STRING( &constant_bin[ 174128 ], 2, 1 );
    const_str_plain_y1 = UNSTREAM_STRING( &constant_bin[ 174415 ], 2, 1 );
    const_str_plain_y2 = UNSTREAM_STRING( &constant_bin[ 198202 ], 2, 1 );
    const_str_plain_y3 = UNSTREAM_STRING( &constant_bin[ 198204 ], 2, 1 );
    const_str_plain_INF = UNSTREAM_STRING( &constant_bin[ 198206 ], 3, 1 );
    const_str_plain_KWD = UNSTREAM_STRING( &constant_bin[ 198209 ], 3, 1 );
    const_str_plain_LIT = UNSTREAM_STRING( &constant_bin[ 176964 ], 3, 1 );
    const_str_plain_abs = UNSTREAM_STRING( &constant_bin[ 6279 ], 3, 1 );
    const_str_plain_add = UNSTREAM_STRING( &constant_bin[ 5896 ], 3, 1 );
    const_str_plain_adv = UNSTREAM_STRING( &constant_bin[ 174617 ], 3, 1 );
    const_str_plain_buf = UNSTREAM_STRING( &constant_bin[ 4503 ], 3, 1 );
    const_str_plain_cid = UNSTREAM_STRING( &constant_bin[ 4511 ], 3, 1 );
    const_str_plain_ctm = UNSTREAM_STRING( &constant_bin[ 187176 ], 3, 1 );
    const_str_plain_def = UNSTREAM_STRING( &constant_bin[ 5834 ], 3, 1 );
    const_str_plain_dic = UNSTREAM_STRING( &constant_bin[ 2316 ], 3, 1 );
    const_str_plain_doc = UNSTREAM_STRING( &constant_bin[ 130569 ], 3, 1 );
    const_str_plain_enc = UNSTREAM_STRING( &constant_bin[ 873 ], 3, 1 );
    const_str_plain_end = UNSTREAM_STRING( &constant_bin[ 665 ], 3, 1 );
    const_str_plain_get = UNSTREAM_STRING( &constant_bin[ 64 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING( &constant_bin[ 369 ], 3, 1 );
    const_str_plain_key = UNSTREAM_STRING( &constant_bin[ 5388 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING( &constant_bin[ 664 ], 3, 1 );
    const_str_plain_map = UNSTREAM_STRING( &constant_bin[ 4580 ], 3, 1 );
    const_str_plain_max = UNSTREAM_STRING( &constant_bin[ 138 ], 3, 1 );
    const_str_plain_min = UNSTREAM_STRING( &constant_bin[ 729 ], 3, 1 );
    const_str_plain_new = UNSTREAM_STRING( &constant_bin[ 6359 ], 3, 1 );
    const_str_plain_obj = UNSTREAM_STRING( &constant_bin[ 5625 ], 3, 1 );
    const_str_plain_out = UNSTREAM_STRING( &constant_bin[ 151 ], 3, 1 );
    const_str_plain_pop = UNSTREAM_STRING( &constant_bin[ 124610 ], 3, 1 );
    const_str_plain_pos = UNSTREAM_STRING( &constant_bin[ 2879 ], 3, 1 );
    const_str_plain_pts = UNSTREAM_STRING( &constant_bin[ 86 ], 3, 1 );
    const_str_plain_run = UNSTREAM_STRING( &constant_bin[ 4989 ], 3, 1 );
    const_str_plain_seq = UNSTREAM_STRING( &constant_bin[ 113968 ], 3, 1 );
    const_str_plain_sub = UNSTREAM_STRING( &constant_bin[ 73605 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING( &constant_bin[ 120551 ], 3, 1 );
    const_str_plain_sys = UNSTREAM_STRING( &constant_bin[ 179461 ], 3, 1 );
    const_str_plain_tag = UNSTREAM_STRING( &constant_bin[ 28 ], 3, 1 );
    const_str_plain_zip = UNSTREAM_STRING( &constant_bin[ 6129 ], 3, 1 );
    const_str_plain_CMap = UNSTREAM_STRING( &constant_bin[ 4537 ], 4, 1 );
    const_str_plain_Kids = UNSTREAM_STRING( &constant_bin[ 190366 ], 4, 1 );
    const_str_plain_Type = UNSTREAM_STRING( &constant_bin[ 7336 ], 4, 1 );
    const_str_plain_args = UNSTREAM_STRING( &constant_bin[ 94 ], 4, 1 );
    const_str_plain_argv = UNSTREAM_STRING( &constant_bin[ 55 ], 4, 1 );
    const_str_plain_bbox = UNSTREAM_STRING( &constant_bin[ 6171 ], 4, 1 );
    const_str_plain_bits = UNSTREAM_STRING( &constant_bin[ 3521 ], 4, 1 );
    const_str_plain_char = UNSTREAM_STRING( &constant_bin[ 493 ], 4, 1 );
    const_str_plain_cmap = UNSTREAM_STRING( &constant_bin[ 4579 ], 4, 1 );
    const_str_plain_code = UNSTREAM_STRING( &constant_bin[ 236 ], 4, 1 );
    const_str_plain_copy = UNSTREAM_STRING( &constant_bin[ 73264 ], 4, 1 );
    const_str_plain_data = UNSTREAM_STRING( &constant_bin[ 2228 ], 4, 1 );
    const_str_plain_dict = UNSTREAM_STRING( &constant_bin[ 179088 ], 4, 1 );
    const_str_plain_diff = UNSTREAM_STRING( &constant_bin[ 1532 ], 4, 1 );
    const_str_plain_done = UNSTREAM_STRING( &constant_bin[ 198212 ], 4, 1 );
    const_str_plain_fill = UNSTREAM_STRING( &constant_bin[ 62236 ], 4, 1 );
    const_str_plain_find = UNSTREAM_STRING( &constant_bin[ 1376 ], 4, 1 );
    const_str_plain_font = UNSTREAM_STRING( &constant_bin[ 6824 ], 4, 1 );
    const_str_plain_func = UNSTREAM_STRING( &constant_bin[ 174151 ], 4, 1 );
    const_str_plain_gray = UNSTREAM_STRING( &constant_bin[ 198216 ], 4, 1 );
    const_str_plain_info = UNSTREAM_STRING( &constant_bin[ 4782 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING( &constant_bin[ 182 ], 4, 1 );
    const_str_plain_join = UNSTREAM_STRING( &constant_bin[ 67797 ], 4, 1 );
    const_str_plain_keys = UNSTREAM_STRING( &constant_bin[ 178314 ], 4, 1 );
    const_str_plain_line = UNSTREAM_STRING( &constant_bin[ 510 ], 4, 1 );
    const_str_plain_long = UNSTREAM_STRING( &constant_bin[ 68500 ], 4, 1 );
    const_str_plain_main = UNSTREAM_STRING( &constant_bin[ 1239 ], 4, 1 );
    const_str_plain_mode = UNSTREAM_STRING( &constant_bin[ 227 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING( &constant_bin[ 353 ], 4, 1 );
    const_str_plain_objs = UNSTREAM_STRING( &constant_bin[ 5633 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING( &constant_bin[ 4839 ], 4, 1 );
    const_str_plain_pack = UNSTREAM_STRING( &constant_bin[ 197655 ], 4, 1 );
    const_str_plain_page = UNSTREAM_STRING( &constant_bin[ 126 ], 4, 1 );
    const_str_plain_path = UNSTREAM_STRING( &constant_bin[ 5801 ], 4, 1 );
    const_str_plain_pos0 = UNSTREAM_STRING( &constant_bin[ 198220 ], 4, 1 );
    const_str_plain_pred = UNSTREAM_STRING( &constant_bin[ 191781 ], 4, 1 );
    const_str_plain_push = UNSTREAM_STRING( &constant_bin[ 187647 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING( &constant_bin[ 2425 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING( &constant_bin[ 103102 ], 4, 1 );
    const_str_plain_rise = UNSTREAM_STRING( &constant_bin[ 89139 ], 4, 1 );
    const_str_plain_save = UNSTREAM_STRING( &constant_bin[ 198224 ], 4, 1 );
    const_str_plain_seek = UNSTREAM_STRING( &constant_bin[ 191384 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING( &constant_bin[ 5560 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING( &constant_bin[ 4823 ], 4, 1 );
    const_str_plain_size = UNSTREAM_STRING( &constant_bin[ 6844 ], 4, 1 );
    const_str_plain_spec = UNSTREAM_STRING( &constant_bin[ 1651 ], 4, 1 );
    const_str_plain_strm = UNSTREAM_STRING( &constant_bin[ 176259 ], 4, 1 );
    const_str_plain_tell = UNSTREAM_STRING( &constant_bin[ 198228 ], 4, 1 );
    const_str_plain_text = UNSTREAM_STRING( &constant_bin[ 612 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING( &constant_bin[ 166 ], 4, 1 );
    const_str_plain_uniq = UNSTREAM_STRING( &constant_bin[ 189581 ], 4, 1 );
    const_str_plain_xref = UNSTREAM_STRING( &constant_bin[ 176520 ], 4, 1 );
    const_list_int_0_list = PyList_New( 1 );
    PyList_SET_ITEM( const_list_int_0_list, 0, const_int_0 ); Py_INCREF( const_int_0 );
    const_str_plain_Image = UNSTREAM_STRING( &constant_bin[ 165790 ], 5, 1 );
    const_str_plain_PSEOF = UNSTREAM_STRING( &constant_bin[ 198232 ], 5, 1 );
    const_str_plain_Plane = UNSTREAM_STRING( &constant_bin[ 197696 ], 5, 1 );
    const_str_plain_Width = UNSTREAM_STRING( &constant_bin[ 179442 ], 5, 1 );
    const_str_plain__objs = UNSTREAM_STRING( &constant_bin[ 176287 ], 5, 1 );
    const_str_plain_array = UNSTREAM_STRING( &constant_bin[ 176870 ], 5, 1 );
    const_str_plain_attrs = UNSTREAM_STRING( &constant_bin[ 189615 ], 5, 1 );
    const_str_plain_begin = UNSTREAM_STRING( &constant_bin[ 4506 ], 5, 1 );
    const_str_plain_bytes = UNSTREAM_STRING( &constant_bin[ 1476 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING( &constant_bin[ 66646 ], 5, 1 );
    const_str_plain_codec = UNSTREAM_STRING( &constant_bin[ 236 ], 5, 1 );
    const_str_plain_csort = UNSTREAM_STRING( &constant_bin[ 198237 ], 5, 1 );
    const_str_plain_debug = UNSTREAM_STRING( &constant_bin[ 103 ], 5, 1 );
    const_str_plain_flush = UNSTREAM_STRING( &constant_bin[ 2865 ], 5, 1 );
    const_str_plain_fname = UNSTREAM_STRING( &constant_bin[ 352 ], 5, 1 );
    const_str_plain_genno = UNSTREAM_STRING( &constant_bin[ 198242 ], 5, 1 );
    const_str_plain_group = UNSTREAM_STRING( &constant_bin[ 6341 ], 5, 1 );
    const_str_plain_image = UNSTREAM_STRING( &constant_bin[ 175 ], 5, 1 );
    const_str_plain_index = UNSTREAM_STRING( &constant_bin[ 1877 ], 5, 1 );
    const_str_plain_klass = UNSTREAM_STRING( &constant_bin[ 198247 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING( &constant_bin[ 198252 ], 5, 1 );
    const_str_plain_match = UNSTREAM_STRING( &constant_bin[ 178759 ], 5, 1 );
    const_str_plain_names = UNSTREAM_STRING( &constant_bin[ 8133 ], 5, 1 );
    const_str_plain_objid = UNSTREAM_STRING( &constant_bin[ 176204 ], 5, 1 );
    const_str_plain_outfp = UNSTREAM_STRING( &constant_bin[ 331 ], 5, 1 );
    const_str_plain_props = UNSTREAM_STRING( &constant_bin[ 198257 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING( &constant_bin[ 4524 ], 5, 1 );
    const_str_plain_reset = UNSTREAM_STRING( &constant_bin[ 3547 ], 5, 1 );
    const_str_plain_scale = UNSTREAM_STRING( &constant_bin[ 257 ], 5, 1 );
    const_str_plain_split = UNSTREAM_STRING( &constant_bin[ 198262 ], 5, 1 );
    const_str_plain_start = UNSTREAM_STRING( &constant_bin[ 176846 ], 5, 1 );
    const_str_plain_token = UNSTREAM_STRING( &constant_bin[ 5577 ], 5, 1 );
    const_str_plain_utils = UNSTREAM_STRING( &constant_bin[ 197349 ], 5, 1 );
    const_str_plain_width = UNSTREAM_STRING( &constant_bin[ 6228 ], 5, 1 );
    const_str_plain_write = UNSTREAM_STRING( &constant_bin[ 180 ], 5, 1 );
    const_str_plain_xrefs = UNSTREAM_STRING( &constant_bin[ 198267 ], 5, 1 );
    const_str_angle_lambda = UNSTREAM_STRING( &constant_bin[ 198272 ], 8, 0 );
    const_str_plain_BUFSIZ = UNSTREAM_STRING( &constant_bin[ 198280 ], 6, 1 );
    const_str_plain_CMapDB = UNSTREAM_STRING( &constant_bin[ 198286 ], 6, 1 );
    const_str_plain_Filter = UNSTREAM_STRING( &constant_bin[ 198292 ], 6, 1 );
    const_str_plain_Height = UNSTREAM_STRING( &constant_bin[ 8646 ], 6, 1 );
    const_str_plain_LTChar = UNSTREAM_STRING( &constant_bin[ 198298 ], 6, 1 );
    const_str_plain_LTLine = UNSTREAM_STRING( &constant_bin[ 198304 ], 6, 1 );
    const_str_plain_LTPage = UNSTREAM_STRING( &constant_bin[ 198310 ], 6, 1 );
    const_str_plain_LTRect = UNSTREAM_STRING( &constant_bin[ 198316 ], 6, 1 );
    const_str_plain_LTText = UNSTREAM_STRING( &constant_bin[ 173994 ], 6, 1 );
    const_str_plain_Length = UNSTREAM_STRING( &constant_bin[ 179553 ], 6, 1 );
    const_str_plain_STRICT = UNSTREAM_STRING( &constant_bin[ 198322 ], 6, 1 );
    const_str_plain__stack = UNSTREAM_STRING( &constant_bin[ 198328 ], 6, 1 );
    const_str_plain_append = UNSTREAM_STRING( &constant_bin[ 198334 ], 6, 1 );
    const_str_plain_bufpos = UNSTREAM_STRING( &constant_bin[ 192823 ], 6, 1 );
    const_str_plain_cmapdb = UNSTREAM_STRING( &constant_bin[ 5543 ], 6, 1 );
    const_str_plain_colors = UNSTREAM_STRING( &constant_bin[ 7538 ], 6, 1 );
    const_str_plain_decode = UNSTREAM_STRING( &constant_bin[ 1289 ], 6, 1 );
    const_str_plain_do_tag = UNSTREAM_STRING( &constant_bin[ 198340 ], 6, 1 );
    const_str_plain_encode = UNSTREAM_STRING( &constant_bin[ 873 ], 6, 1 );
    const_str_plain_exists = UNSTREAM_STRING( &constant_bin[ 164711 ], 6, 1 );
    const_str_plain_extend = UNSTREAM_STRING( &constant_bin[ 198346 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING( &constant_bin[ 4784 ], 6, 1 );
    const_str_plain_fsplit = UNSTREAM_STRING( &constant_bin[ 198352 ], 6, 1 );
    const_str_plain_getobj = UNSTREAM_STRING( &constant_bin[ 176938 ], 6, 1 );
    const_str_plain_groups = UNSTREAM_STRING( &constant_bin[ 6341 ], 6, 1 );
    const_str_plain_height = UNSTREAM_STRING( &constant_bin[ 6322 ], 6, 1 );
    const_str_plain_ignore = UNSTREAM_STRING( &constant_bin[ 2269 ], 6, 1 );
    const_str_plain_length = UNSTREAM_STRING( &constant_bin[ 1596 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING( &constant_bin[ 198358 ], 6, 1 );
    const_str_plain_matrix = UNSTREAM_STRING( &constant_bin[ 174599 ], 6, 1 );
    const_str_plain_normal = UNSTREAM_STRING( &constant_bin[ 177752 ], 6, 1 );
    const_str_plain_offset = UNSTREAM_STRING( &constant_bin[ 7209 ], 6, 1 );
    const_str_plain_pageid = UNSTREAM_STRING( &constant_bin[ 189546 ], 6, 1 );
    const_str_plain_pageno = UNSTREAM_STRING( &constant_bin[ 126 ], 6, 1 );
    const_str_plain_params = UNSTREAM_STRING( &constant_bin[ 296 ], 6, 1 );
    const_str_plain_parser = UNSTREAM_STRING( &constant_bin[ 3766 ], 6, 1 );
    const_str_plain_popall = UNSTREAM_STRING( &constant_bin[ 198364 ], 6, 1 );
    const_str_plain_remove = UNSTREAM_STRING( &constant_bin[ 198370 ], 6, 1 );
    const_str_plain_render = UNSTREAM_STRING( &constant_bin[ 175919 ], 6, 1 );
    const_str_plain_result = UNSTREAM_STRING( &constant_bin[ 7527 ], 6, 1 );
    const_str_plain_rotate = UNSTREAM_STRING( &constant_bin[ 6181 ], 6, 1 );
    const_str_plain_search = UNSTREAM_STRING( &constant_bin[ 198376 ], 6, 1 );
    const_str_plain_sorted = UNSTREAM_STRING( &constant_bin[ 198382 ], 6, 1 );
    const_str_plain_stdout = UNSTREAM_STRING( &constant_bin[ 198388 ], 6, 1 );
    const_str_plain_stream = UNSTREAM_STRING( &constant_bin[ 176069 ], 6, 1 );
    const_str_plain_stroke = UNSTREAM_STRING( &constant_bin[ 62150 ], 6, 1 );
    const_str_plain_struct = UNSTREAM_STRING( &constant_bin[ 190621 ], 6, 1 );
    const_str_plain_unichr = UNSTREAM_STRING( &constant_bin[ 5489 ], 6, 1 );
    const_str_plain_unpack = UNSTREAM_STRING( &constant_bin[ 198394 ], 6, 1 );
    const_str_plain_update = UNSTREAM_STRING( &constant_bin[ 198400 ], 6, 1 );
    const_str_plain_xrange = UNSTREAM_STRING( &constant_bin[ 198406 ], 6, 1 );
    const_tuple_none_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    const_str_angle_genexpr = UNSTREAM_STRING( &constant_bin[ 198412 ], 9, 0 );
    const_str_plain_BytesIO = UNSTREAM_STRING( &constant_bin[ 198421 ], 7, 1 );
    const_str_plain_Columns = UNSTREAM_STRING( &constant_bin[ 198428 ], 7, 1 );
    const_str_plain_LTCurve = UNSTREAM_STRING( &constant_bin[ 198435 ], 7, 1 );
    const_str_plain_LTImage = UNSTREAM_STRING( &constant_bin[ 198442 ], 7, 1 );
    const_str_plain_PDFPage = UNSTREAM_STRING( &constant_bin[ 6601 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING( &constant_bin[ 198449 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING( &constant_bin[ 198456 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING( &constant_bin[ 198463 ], 7, 1 );
    const_str_plain___len__ = UNSTREAM_STRING( &constant_bin[ 198470 ], 7, 1 );
    const_str_plain_analyze = UNSTREAM_STRING( &constant_bin[ 198477 ], 7, 1 );
    const_str_plain_caching = UNSTREAM_STRING( &constant_bin[ 267 ], 7, 1 );
    const_str_plain_catalog = UNSTREAM_STRING( &constant_bin[ 198484 ], 7, 1 );
    const_str_plain_charpos = UNSTREAM_STRING( &constant_bin[ 198491 ], 7, 1 );
    const_str_plain_columns = UNSTREAM_STRING( &constant_bin[ 198498 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING( &constant_bin[ 198505 ], 7, 1 );
    const_str_plain_decrypt = UNSTREAM_STRING( &constant_bin[ 177008 ], 7, 1 );
    const_str_plain_default = UNSTREAM_STRING( &constant_bin[ 179241 ], 7, 1 );
    const_str_plain_dirname = UNSTREAM_STRING( &constant_bin[ 198512 ], 7, 1 );
    const_str_plain_encrypt = UNSTREAM_STRING( &constant_bin[ 1187 ], 7, 1 );
    const_str_plain_end_tag = UNSTREAM_STRING( &constant_bin[ 198519 ], 7, 1 );
    const_str_plain_environ = UNSTREAM_STRING( &constant_bin[ 198526 ], 7, 1 );
    const_str_plain_evenodd = UNSTREAM_STRING( &constant_bin[ 198533 ], 7, 1 );
    const_str_plain_fillbuf = UNSTREAM_STRING( &constant_bin[ 198540 ], 7, 1 );
    const_str_plain_filters = UNSTREAM_STRING( &constant_bin[ 198547 ], 7, 1 );
    const_str_plain_get_any = UNSTREAM_STRING( &constant_bin[ 198554 ], 7, 1 );
    const_str_plain_get_pts = UNSTREAM_STRING( &constant_bin[ 198561 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING( &constant_bin[ 198568 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING( &constant_bin[ 198575 ], 7, 1 );
    const_str_plain_leading = UNSTREAM_STRING( &constant_bin[ 187417 ], 7, 1 );
    const_str_plain_linepos = UNSTREAM_STRING( &constant_bin[ 198582 ], 7, 1 );
    const_str_plain_logging = UNSTREAM_STRING( &constant_bin[ 198589 ], 7, 1 );
    const_str_plain_nunpack = UNSTREAM_STRING( &constant_bin[ 198596 ], 7, 1 );
    const_str_plain_offsets = UNSTREAM_STRING( &constant_bin[ 177058 ], 7, 1 );
    const_str_plain_pdffont = UNSTREAM_STRING( &constant_bin[ 179290 ], 7, 1 );
    const_str_plain_replace = UNSTREAM_STRING( &constant_bin[ 198112 ], 7, 1 );
    const_str_plain_rsrcmgr = UNSTREAM_STRING( &constant_bin[ 319 ], 7, 1 );
    const_str_plain_scaling = UNSTREAM_STRING( &constant_bin[ 174732 ], 7, 1 );
    const_str_plain_set_ctm = UNSTREAM_STRING( &constant_bin[ 198603 ], 7, 1 );
    const_str_plain_srcsize = UNSTREAM_STRING( &constant_bin[ 198610 ], 7, 1 );
    const_tuple_false_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_false_tuple, 0, Py_False ); Py_INCREF( Py_False );
    const_tuple_int_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    const_str_plain_ENCODING = UNSTREAM_STRING( &constant_bin[ 185233 ], 8, 1 );
    const_str_plain_Encoding = UNSTREAM_STRING( &constant_bin[ 8104 ], 8, 1 );
    const_str_plain_LAParams = UNSTREAM_STRING( &constant_bin[ 173918 ], 8, 1 );
    const_str_plain_LTFigure = UNSTREAM_STRING( &constant_bin[ 198617 ], 8, 1 );
    const_str_plain_PSObject = UNSTREAM_STRING( &constant_bin[ 198625 ], 8, 1 );
    const_str_plain_TestCase = UNSTREAM_STRING( &constant_bin[ 198633 ], 8, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING( &constant_bin[ 198641 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING( &constant_bin[ 198649 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING( &constant_bin[ 198657 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING( &constant_bin[ 777 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING( &constant_bin[ 198665 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING( &constant_bin[ 198673 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING( &constant_bin[ 198681 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING( &constant_bin[ 198689 ], 8, 1 );
    const_str_plain___repr__ = UNSTREAM_STRING( &constant_bin[ 198697 ], 8, 1 );
    const_str_plain_bbox2str = UNSTREAM_STRING( &constant_bin[ 198705 ], 8, 1 );
    const_str_plain_choplist = UNSTREAM_STRING( &constant_bin[ 198713 ], 8, 1 );
    const_str_plain_contents = UNSTREAM_STRING( &constant_bin[ 187140 ], 8, 1 );
    const_str_plain_decipher = UNSTREAM_STRING( &constant_bin[ 191999 ], 8, 1 );
    const_str_plain_end_page = UNSTREAM_STRING( &constant_bin[ 198721 ], 8, 1 );
    const_str_plain_end_type = UNSTREAM_STRING( &constant_bin[ 193701 ], 8, 1 );
    const_str_plain_exc_type = UNSTREAM_STRING( &constant_bin[ 198729 ], 8, 1 );
    const_str_plain_fallback = UNSTREAM_STRING( &constant_bin[ 191314 ], 8, 1 );
    const_str_plain_fontname = UNSTREAM_STRING( &constant_bin[ 198737 ], 8, 1 );
    const_str_plain_fontsize = UNSTREAM_STRING( &constant_bin[ 174719 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING( &constant_bin[ 198745 ], 8, 1 );
    const_str_plain_get_cmap = UNSTREAM_STRING( &constant_bin[ 198753 ], 8, 1 );
    const_str_plain_get_data = UNSTREAM_STRING( &constant_bin[ 198761 ], 8, 1 );
    const_str_plain_get_text = UNSTREAM_STRING( &constant_bin[ 198769 ], 8, 1 );
    const_str_plain_isnumber = UNSTREAM_STRING( &constant_bin[ 198777 ], 8, 1 );
    const_str_plain_laparams = UNSTREAM_STRING( &constant_bin[ 294 ], 8, 1 );
    const_str_plain_maxpages = UNSTREAM_STRING( &constant_bin[ 138 ], 8, 1 );
    const_str_plain_mediabox = UNSTREAM_STRING( &constant_bin[ 189845 ], 8, 1 );
    const_str_plain_nextline = UNSTREAM_STRING( &constant_bin[ 193751 ], 8, 1 );
    const_str_plain_password = UNSTREAM_STRING( &constant_bin[ 113 ], 8, 1 );
    const_str_plain_pdfcolor = UNSTREAM_STRING( &constant_bin[ 175707 ], 8, 1 );
    const_str_plain_pdftypes = UNSTREAM_STRING( &constant_bin[ 191479 ], 8, 1 );
    const_str_plain_psparser = UNSTREAM_STRING( &constant_bin[ 192947 ], 8, 1 );
    const_str_plain_resolve1 = UNSTREAM_STRING( &constant_bin[ 198785 ], 8, 1 );
    const_str_plain_rldecode = UNSTREAM_STRING( &constant_bin[ 195954 ], 8, 1 );
    const_str_plain_unittest = UNSTREAM_STRING( &constant_bin[ 198793 ], 8, 1 );
    const_str_plain_vertical = UNSTREAM_STRING( &constant_bin[ 3043 ], 8, 1 );
    const_str_plain_LTTextBox = UNSTREAM_STRING( &constant_bin[ 174063 ], 9, 1 );
    const_str_plain_PDFDevice = UNSTREAM_STRING( &constant_bin[ 175893 ], 9, 1 );
    const_str_plain_PDFObjRef = UNSTREAM_STRING( &constant_bin[ 192322 ], 9, 1 );
    const_str_plain_PDFParser = UNSTREAM_STRING( &constant_bin[ 178500 ], 9, 1 );
    const_str_plain_PDFStream = UNSTREAM_STRING( &constant_bin[ 189681 ], 9, 1 );
    const_str_plain_PSKeyword = UNSTREAM_STRING( &constant_bin[ 193534 ], 9, 1 );
    const_str_plain_PSLiteral = UNSTREAM_STRING( &constant_bin[ 193424 ], 9, 1 );
    const_str_plain_Resources = UNSTREAM_STRING( &constant_bin[ 4883 ], 9, 1 );
    const_str_plain_ToUnicode = UNSTREAM_STRING( &constant_bin[ 198801 ], 9, 1 );
    const_str_plain___class__ = UNSTREAM_STRING( &constant_bin[ 198810 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING( &constant_bin[ 198819 ], 9, 1 );
    const_str_plain_all_texts = UNSTREAM_STRING( &constant_bin[ 173981 ], 9, 1 );
    const_str_plain_begin_tag = UNSTREAM_STRING( &constant_bin[ 198828 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING( &constant_bin[ 198837 ], 9, 1 );
    const_str_plain_char_disp = UNSTREAM_STRING( &constant_bin[ 198846 ], 9, 1 );
    const_str_plain_charspace = UNSTREAM_STRING( &constant_bin[ 175862 ], 9, 1 );
    const_str_plain_exc_value = UNSTREAM_STRING( &constant_bin[ 198855 ], 9, 1 );
    const_str_plain_get_bound = UNSTREAM_STRING( &constant_bin[ 198864 ], 9, 1 );
    const_str_plain_get_pages = UNSTREAM_STRING( &constant_bin[ 198873 ], 9, 1 );
    const_str_plain_get_width = UNSTREAM_STRING( &constant_bin[ 179483 ], 9, 1 );
    const_str_plain_int_value = UNSTREAM_STRING( &constant_bin[ 198882 ], 9, 1 );
    const_str_plain_iteritems = UNSTREAM_STRING( &constant_bin[ 198891 ], 9, 1 );
    const_str_plain_linewidth = UNSTREAM_STRING( &constant_bin[ 6357 ], 9, 1 );
    const_str_plain_lzwdecode = UNSTREAM_STRING( &constant_bin[ 175629 ], 9, 1 );
    const_str_plain_nexttoken = UNSTREAM_STRING( &constant_bin[ 194730 ], 9, 1 );
    const_str_plain_num_value = UNSTREAM_STRING( &constant_bin[ 198900 ], 9, 1 );
    const_str_plain_pdfparser = UNSTREAM_STRING( &constant_bin[ 190853 ], 9, 1 );
    const_str_plain_resources = UNSTREAM_STRING( &constant_bin[ 187150 ], 9, 1 );
    const_str_plain_set_objid = UNSTREAM_STRING( &constant_bin[ 198909 ], 9, 1 );
    const_str_plain_startxref = UNSTREAM_STRING( &constant_bin[ 198918 ], 9, 1 );
    const_str_plain_str_value = UNSTREAM_STRING( &constant_bin[ 198927 ], 9, 1 );
    const_str_plain_textstate = UNSTREAM_STRING( &constant_bin[ 198936 ], 9, 1 );
    const_str_plain_to_unichr = UNSTREAM_STRING( &constant_bin[ 198945 ], 9, 1 );
    const_str_plain_wordspace = UNSTREAM_STRING( &constant_bin[ 187390 ], 9, 1 );
    const_str_plain_CMapParser = UNSTREAM_STRING( &constant_bin[ 198954 ], 10, 1 );
    const_str_plain_ColorSpace = UNSTREAM_STRING( &constant_bin[ 175793 ], 10, 1 );
    const_str_plain_EncodingDB = UNSTREAM_STRING( &constant_bin[ 198964 ], 10, 1 );
    const_str_plain_LTTextLine = UNSTREAM_STRING( &constant_bin[ 175152 ], 10, 1 );
    const_str_plain_PDFCIDFont = UNSTREAM_STRING( &constant_bin[ 186680 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING( &constant_bin[ 198974 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING( &constant_bin[ 3314 ], 10, 1 );
    const_str_plain_begin_page = UNSTREAM_STRING( &constant_bin[ 198984 ], 10, 1 );
    const_str_plain_boxes_flow = UNSTREAM_STRING( &constant_bin[ 544 ], 10, 1 );
    const_str_plain_char_width = UNSTREAM_STRING( &constant_bin[ 198994 ], 10, 1 );
    const_str_plain_colorspace = UNSTREAM_STRING( &constant_bin[ 186918 ], 10, 1 );
    const_str_plain_dict_value = UNSTREAM_STRING( &constant_bin[ 199004 ], 10, 1 );
    const_str_plain_do_keyword = UNSTREAM_STRING( &constant_bin[ 5385 ], 10, 1 );
    const_str_plain_encodingdb = UNSTREAM_STRING( &constant_bin[ 8006 ], 10, 1 );
    const_str_plain_end_figure = UNSTREAM_STRING( &constant_bin[ 199014 ], 10, 1 );
    const_str_plain_get_height = UNSTREAM_STRING( &constant_bin[ 199024 ], 10, 1 );
    const_str_plain_get_objids = UNSTREAM_STRING( &constant_bin[ 199034 ], 10, 1 );
    const_str_plain_get_unichr = UNSTREAM_STRING( &constant_bin[ 5485 ], 10, 1 );
    const_str_plain_layoutmode = UNSTREAM_STRING( &constant_bin[ 221 ], 10, 1 );
    const_str_plain_linematrix = UNSTREAM_STRING( &constant_bin[ 187461 ], 10, 1 );
    const_str_plain_list_value = UNSTREAM_STRING( &constant_bin[ 199044 ], 10, 1 );
    const_str_plain_matrix2str = UNSTREAM_STRING( &constant_bin[ 199054 ], 10, 1 );
    const_str_plain_nextobject = UNSTREAM_STRING( &constant_bin[ 191410 ], 10, 1 );
    const_str_plain_paint_path = UNSTREAM_STRING( &constant_bin[ 199064 ], 10, 1 );
    const_str_plain_start_type = UNSTREAM_STRING( &constant_bin[ 194172 ], 10, 1 );
    const_str_plain_startswith = UNSTREAM_STRING( &constant_bin[ 199074 ], 10, 1 );
    const_str_plain_ImageWriter = UNSTREAM_STRING( &constant_bin[ 199084 ], 11, 1 );
    const_str_plain_KEYWORD_DEF = UNSTREAM_STRING( &constant_bin[ 5059 ], 11, 1 );
    const_str_plain_KEYWORD_OBJ = UNSTREAM_STRING( &constant_bin[ 199095 ], 11, 1 );
    const_str_plain_LTContainer = UNSTREAM_STRING( &constant_bin[ 199106 ], 11, 1 );
    const_str_plain_LTTextGroup = UNSTREAM_STRING( &constant_bin[ 173994 ], 11, 1 );
    const_str_plain_PDFDocument = UNSTREAM_STRING( &constant_bin[ 176212 ], 11, 1 );
    const_str_plain_PSException = UNSTREAM_STRING( &constant_bin[ 199117 ], 11, 1 );
    const_str_plain_PSTypeError = UNSTREAM_STRING( &constant_bin[ 199128 ], 11, 1 );
    const_str_plain___delattr__ = UNSTREAM_STRING( &constant_bin[ 199139 ], 11, 1 );
    const_str_plain___getattr__ = UNSTREAM_STRING( &constant_bin[ 199150 ], 11, 1 );
    const_str_plain___getitem__ = UNSTREAM_STRING( &constant_bin[ 199161 ], 11, 1 );
    const_str_plain___package__ = UNSTREAM_STRING( &constant_bin[ 199172 ], 11, 1 );
    const_str_plain___setattr__ = UNSTREAM_STRING( &constant_bin[ 199183 ], 11, 1 );
    const_str_plain_add_results = UNSTREAM_STRING( &constant_bin[ 192717 ], 11, 1 );
    const_str_plain_assertEqual = UNSTREAM_STRING( &constant_bin[ 199194 ], 11, 1 );
    const_str_plain_char_margin = UNSTREAM_STRING( &constant_bin[ 493 ], 11, 1 );
    const_str_plain_cid2unicode = UNSTREAM_STRING( &constant_bin[ 184626 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING( &constant_bin[ 199205 ], 11, 1 );
    const_str_plain_decode_text = UNSTREAM_STRING( &constant_bin[ 199216 ], 11, 1 );
    const_str_plain_get_descent = UNSTREAM_STRING( &constant_bin[ 199227 ], 11, 1 );
    const_str_plain_get_filters = UNSTREAM_STRING( &constant_bin[ 199238 ], 11, 1 );
    const_str_plain_get_rawdata = UNSTREAM_STRING( &constant_bin[ 199249 ], 11, 1 );
    const_str_plain_imagewriter = UNSTREAM_STRING( &constant_bin[ 175 ], 11, 1 );
    const_str_plain_is_vertical = UNSTREAM_STRING( &constant_bin[ 199260 ], 11, 1 );
    const_str_plain_line_margin = UNSTREAM_STRING( &constant_bin[ 510 ], 11, 1 );
    const_str_plain_mult_matrix = UNSTREAM_STRING( &constant_bin[ 199271 ], 11, 1 );
    const_str_plain_ncomponents = UNSTREAM_STRING( &constant_bin[ 175809 ], 11, 1 );
    const_str_plain_render_char = UNSTREAM_STRING( &constant_bin[ 199282 ], 11, 1 );
    const_str_plain_word_margin = UNSTREAM_STRING( &constant_bin[ 527 ], 11, 1 );
    const_tuple_int_neg_1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_neg_1_tuple, 0, const_int_neg_1 ); Py_INCREF( const_int_neg_1 );
    const_tuple_int_pos_1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_int_pos_2_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_2_tuple, 0, const_int_pos_2 ); Py_INCREF( const_int_pos_2 );
    const_tuple_int_pos_3_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_tuple, 0, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    const_tuple_int_pos_4_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_4_tuple, 0, const_int_pos_4 ); Py_INCREF( const_int_pos_4 );
    const_tuple_str_space_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_space_tuple, 0, const_str_space ); Py_INCREF( const_str_space );
    const_str_plain_CMapNotFound = UNSTREAM_STRING( &constant_bin[ 199293 ], 12, 1 );
    const_str_plain_FONT_METRICS = UNSTREAM_STRING( &constant_bin[ 199305 ], 12, 1 );
    const_str_plain_KEYWORD_XREF = UNSTREAM_STRING( &constant_bin[ 199317 ], 12, 1 );
    const_str_plain_PDFException = UNSTREAM_STRING( &constant_bin[ 199329 ], 12, 1 );
    const_str_plain_PDFFontError = UNSTREAM_STRING( &constant_bin[ 199341 ], 12, 1 );
    const_str_plain_PDFType1Font = UNSTREAM_STRING( &constant_bin[ 179344 ], 12, 1 );
    const_str_plain_PDFType3Font = UNSTREAM_STRING( &constant_bin[ 179060 ], 12, 1 );
    const_str_plain_PDFTypeError = UNSTREAM_STRING( &constant_bin[ 199353 ], 12, 1 );
    const_str_plain_TagExtractor = UNSTREAM_STRING( &constant_bin[ 199365 ], 12, 1 );
    const_str_plain_XMLConverter = UNSTREAM_STRING( &constant_bin[ 199377 ], 12, 1 );
    const_str_plain___builtins__ = UNSTREAM_STRING( &constant_bin[ 199389 ], 12, 1 );
    const_str_plain___contains__ = UNSTREAM_STRING( &constant_bin[ 199401 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING( &constant_bin[ 199413 ], 12, 1 );
    const_str_plain_begin_figure = UNSTREAM_STRING( &constant_bin[ 199425 ], 12, 1 );
    const_str_plain_decipher_all = UNSTREAM_STRING( &constant_bin[ 199437 ], 12, 1 );
    const_str_plain_export_image = UNSTREAM_STRING( &constant_bin[ 199449 ], 12, 1 );
    const_str_plain_get_encoding = UNSTREAM_STRING( &constant_bin[ 199461 ], 12, 1 );
    const_str_plain_graphicstate = UNSTREAM_STRING( &constant_bin[ 199473 ], 12, 1 );
    const_str_plain_is_multibyte = UNSTREAM_STRING( &constant_bin[ 199485 ], 12, 1 );
    const_str_plain_keyword_name = UNSTREAM_STRING( &constant_bin[ 199497 ], 12, 1 );
    const_str_plain_literal_name = UNSTREAM_STRING( &constant_bin[ 199509 ], 12, 1 );
    const_str_plain_name2unicode = UNSTREAM_STRING( &constant_bin[ 199521 ], 12, 1 );
    const_str_plain_process_page = UNSTREAM_STRING( &constant_bin[ 188402 ], 12, 1 );
    const_str_plain_render_image = UNSTREAM_STRING( &constant_bin[ 199533 ], 12, 1 );
    const_str_plain_revreadlines = UNSTREAM_STRING( &constant_bin[ 199545 ], 12, 1 );
    const_str_plain_set_document = UNSTREAM_STRING( &constant_bin[ 191142 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING( &constant_bin[ 199557 ], 12, 1 );
    const_str_plain_stream_value = UNSTREAM_STRING( &constant_bin[ 199569 ], 12, 1 );
    const_str_plain_stripcontrol = UNSTREAM_STRING( &constant_bin[ 204 ], 12, 1 );
    const_str_plain_HTMLConverter = UNSTREAM_STRING( &constant_bin[ 199581 ], 13, 1 );
    const_str_plain_PDFColorSpace = UNSTREAM_STRING( &constant_bin[ 175790 ], 13, 1 );
    const_str_plain_PDFTextDevice = UNSTREAM_STRING( &constant_bin[ 199594 ], 13, 1 );
    const_str_plain_PSStackParser = UNSTREAM_STRING( &constant_bin[ 199607 ], 13, 1 );
    const_str_plain_PSSyntaxError = UNSTREAM_STRING( &constant_bin[ 199620 ], 13, 1 );
    const_str_plain_TextConverter = UNSTREAM_STRING( &constant_bin[ 199633 ], 13, 1 );
    const_str_plain___metaclass__ = UNSTREAM_STRING( &constant_bin[ 199646 ], 13, 1 );
    const_str_plain_ascii85decode = UNSTREAM_STRING( &constant_bin[ 1910 ], 13, 1 );
    const_str_plain_exc_traceback = UNSTREAM_STRING( &constant_bin[ 199659 ], 13, 1 );
    const_str_plain_render_string = UNSTREAM_STRING( &constant_bin[ 175919 ], 13, 1 );
    const_tuple_int_0_int_0_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 1, const_int_0 ); Py_INCREF( const_int_0 );
    const_tuple_str_newline_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_newline_tuple, 0, const_str_newline ); Py_INCREF( const_str_newline );
    const_tuple_str_plain_x_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_x_tuple, 0, const_str_plain_x ); Py_INCREF( const_str_plain_x );
    const_tuple_type_object_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type ); Py_INCREF( (PyObject *)&PyBaseObject_Type );
    const_str_plain_FileUnicodeMap = UNSTREAM_STRING( &constant_bin[ 199672 ], 14, 1 );
    const_str_plain_PDFDocEncoding = UNSTREAM_STRING( &constant_bin[ 197365 ], 14, 1 );
    const_str_plain_PDFSyntaxError = UNSTREAM_STRING( &constant_bin[ 199686 ], 14, 1 );
    const_str_plain_add_cid2unichr = UNSTREAM_STRING( &constant_bin[ 199700 ], 14, 1 );
    const_str_plain_asciihexdecode = UNSTREAM_STRING( &constant_bin[ 2533 ], 14, 1 );
    const_str_plain_ccittfaxdecode = UNSTREAM_STRING( &constant_bin[ 199714 ], 14, 1 );
    const_str_plain_is_extractable = UNSTREAM_STRING( &constant_bin[ 199728 ], 14, 1 );
    const_str_plain_MATRIX_IDENTITY = UNSTREAM_STRING( &constant_bin[ 199742 ], 15, 1 );
    const_str_plain_PDFStreamParser = UNSTREAM_STRING( &constant_bin[ 190523 ], 15, 1 );
    const_str_plain_PDFTrueTypeFont = UNSTREAM_STRING( &constant_bin[ 185247 ], 15, 1 );
    const_str_plain_apply_matrix_pt = UNSTREAM_STRING( &constant_bin[ 197523 ], 15, 1 );
    const_str_plain_detect_vertical = UNSTREAM_STRING( &constant_bin[ 199757 ], 15, 1 );
    const_str_plain_get_unicode_map = UNSTREAM_STRING( &constant_bin[ 199772 ], 15, 1 );
    const_tuple_str_plain_KWD_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_KWD_tuple, 0, const_str_plain_KWD ); Py_INCREF( const_str_plain_KWD );
    const_tuple_str_plain_LIT_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_LIT_tuple, 0, const_str_plain_LIT ); Py_INCREF( const_str_plain_LIT );
    const_tuple_str_plain_def_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_def_tuple, 0, const_str_plain_def ); Py_INCREF( const_str_plain_def );
    const_tuple_str_plain_enc_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_enc_tuple, 0, const_str_plain_enc ); Py_INCREF( const_str_plain_enc );
    const_tuple_str_plain_end_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_end_tuple, 0, const_str_plain_end ); Py_INCREF( const_str_plain_end );
    const_tuple_str_plain_obj_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_obj_tuple, 0, const_str_plain_obj ); Py_INCREF( const_str_plain_obj );
    const_str_plain_BitsPerComponent = UNSTREAM_STRING( &constant_bin[ 199787 ], 16, 1 );
    const_str_plain_StandardEncoding = UNSTREAM_STRING( &constant_bin[ 199803 ], 16, 1 );
    const_str_plain_bitspercomponent = UNSTREAM_STRING( &constant_bin[ 197733 ], 16, 1 );
    const_str_plain_get_writing_mode = UNSTREAM_STRING( &constant_bin[ 199819 ], 16, 1 );
    const_str_plain_translate_matrix = UNSTREAM_STRING( &constant_bin[ 199835 ], 16, 1 );
    const_tuple_str_plain_CMap_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_CMap_tuple, 0, const_str_plain_CMap ); Py_INCREF( const_str_plain_CMap );
    const_tuple_str_plain_Type_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Type_tuple, 0, const_str_plain_Type ); Py_INCREF( const_str_plain_Type );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_str_plain_LTTextBoxVertical = UNSTREAM_STRING( &constant_bin[ 199851 ], 17, 1 );
    const_str_plain_PDFObjectNotFound = UNSTREAM_STRING( &constant_bin[ 199868 ], 17, 1 );
    const_str_plain_apply_matrix_norm = UNSTREAM_STRING( &constant_bin[ 199885 ], 17, 1 );
    const_str_plain_check_extractable = UNSTREAM_STRING( &constant_bin[ 199902 ], 17, 1 );
    const_str_plain_glyphname2unicode = UNSTREAM_STRING( &constant_bin[ 199919 ], 17, 1 );
    const_tuple_str_plain_Image_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Image_tuple, 0, const_str_plain_Image ); Py_INCREF( const_str_plain_Image );
    const_tuple_str_plain_PSEOF_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PSEOF_tuple, 0, const_str_plain_PSEOF ); Py_INCREF( const_str_plain_PSEOF );
    const_tuple_str_plain_begin_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_begin_tuple, 0, const_str_plain_begin ); Py_INCREF( const_str_plain_begin );
    const_str_plain_LITERAL_DEVICE_RGB = UNSTREAM_STRING( &constant_bin[ 199936 ], 18, 1 );
    const_str_plain_PDFPageInterpreter = UNSTREAM_STRING( &constant_bin[ 199954 ], 18, 1 );
    const_str_plain_PDFResourceManager = UNSTREAM_STRING( &constant_bin[ 199972 ], 18, 1 );
    const_tuple_str_plain_CMapDB_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_CMapDB_tuple, 0, const_str_plain_CMapDB ); Py_INCREF( const_str_plain_CMapDB );
    const_tuple_str_plain_STRICT_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_STRICT_tuple, 0, const_str_plain_STRICT ); Py_INCREF( const_str_plain_STRICT );
    const_str_plain_LITERALS_DCT_DECODE = UNSTREAM_STRING( &constant_bin[ 199990 ], 19, 1 );
    const_str_plain_LITERAL_DEVICE_CMYK = UNSTREAM_STRING( &constant_bin[ 200009 ], 19, 1 );
    const_str_plain_LITERAL_DEVICE_GRAY = UNSTREAM_STRING( &constant_bin[ 200028 ], 19, 1 );
    const_str_plain_apply_png_predictor = UNSTREAM_STRING( &constant_bin[ 200047 ], 19, 1 );
    const_tuple_str_plain_BytesIO_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_BytesIO_tuple, 0, const_str_plain_BytesIO ); Py_INCREF( const_str_plain_BytesIO );
    const_tuple_str_plain_nunpack_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_nunpack_tuple, 0, const_str_plain_nunpack ); Py_INCREF( const_str_plain_nunpack );
    const_str_plain_PDFUnicodeNotDefined = UNSTREAM_STRING( &constant_bin[ 200066 ], 20, 1 );
    const_tuple_str_plain_bbox2str_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_bbox2str_tuple, 0, const_str_plain_bbox2str ); Py_INCREF( const_str_plain_bbox2str );
    const_tuple_str_plain_choplist_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_choplist_tuple, 0, const_str_plain_choplist ); Py_INCREF( const_str_plain_choplist );
    const_tuple_str_plain_isnumber_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_isnumber_tuple, 0, const_str_plain_isnumber ); Py_INCREF( const_str_plain_isnumber );
    const_tuple_str_plain_resolve1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_resolve1_tuple, 0, const_str_plain_resolve1 ); Py_INCREF( const_str_plain_resolve1 );
    const_str_plain_PREDEFINED_COLORSPACE = UNSTREAM_STRING( &constant_bin[ 200086 ], 21, 1 );
    const_tuple_int_pos_1_int_pos_1_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_int_pos_1_tuple, 1, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_str_plain_PDFObjRef_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PDFObjRef_tuple, 0, const_str_plain_PDFObjRef ); Py_INCREF( const_str_plain_PDFObjRef );
    const_tuple_str_plain_PDFParser_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PDFParser_tuple, 0, const_str_plain_PDFParser ); Py_INCREF( const_str_plain_PDFParser );
    const_tuple_str_plain_PDFStream_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PDFStream_tuple, 0, const_str_plain_PDFStream ); Py_INCREF( const_str_plain_PDFStream );
    const_tuple_str_plain_PSLiteral_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PSLiteral_tuple, 0, const_str_plain_PSLiteral ); Py_INCREF( const_str_plain_PSLiteral );
    const_tuple_str_plain_int_value_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_int_value_tuple, 0, const_str_plain_int_value ); Py_INCREF( const_str_plain_int_value );
    const_tuple_str_plain_dict_value_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_dict_value_tuple, 0, const_str_plain_dict_value ); Py_INCREF( const_str_plain_dict_value );
    const_tuple_str_plain_list_value_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_list_value_tuple, 0, const_str_plain_list_value ); Py_INCREF( const_str_plain_list_value );
    const_tuple_str_plain_PDFDocument_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PDFDocument_tuple, 0, const_str_plain_PDFDocument ); Py_INCREF( const_str_plain_PDFDocument );
    const_tuple_str_plain_mult_matrix_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_mult_matrix_tuple, 0, const_str_plain_mult_matrix ); Py_INCREF( const_str_plain_mult_matrix );
    const_tuple_str_plain_PDFException_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PDFException_tuple, 0, const_str_plain_PDFException ); Py_INCREF( const_str_plain_PDFException );
    const_tuple_str_plain_literal_name_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_literal_name_tuple, 0, const_str_plain_literal_name ); Py_INCREF( const_str_plain_literal_name );
    const_tuple_str_plain_name2unicode_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_name2unicode_tuple, 0, const_str_plain_name2unicode ); Py_INCREF( const_str_plain_name2unicode );
    const_tuple_str_plain_stream_value_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_stream_value_tuple, 0, const_str_plain_stream_value ); Py_INCREF( const_str_plain_stream_value );
    const_tuple_str_plain_PSStackParser_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PSStackParser_tuple, 0, const_str_plain_PSStackParser ); Py_INCREF( const_str_plain_PSStackParser );
    const_tuple_str_plain_PSSyntaxError_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PSSyntaxError_tuple, 0, const_str_plain_PSSyntaxError ); Py_INCREF( const_str_plain_PSSyntaxError );
    const_str_plain_PDFTextExtractionNotAllowed = UNSTREAM_STRING( &constant_bin[ 200107 ], 27, 1 );
    const_tuple_str_plain_apply_matrix_pt_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_apply_matrix_pt_tuple, 0, const_str_plain_apply_matrix_pt ); Py_INCREF( const_str_plain_apply_matrix_pt );
    const_tuple_str_plain_self_str_plain_i_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_i_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_i_tuple, 1, const_str_plain_i ); Py_INCREF( const_str_plain_i );
    const_tuple_str_plain_self_str_plain_n_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_n_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_n_tuple, 1, const_str_plain_n ); Py_INCREF( const_str_plain_n );
    const_tuple_str_plain_self_str_plain_s_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_s_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_s_tuple, 1, const_str_plain_s ); Py_INCREF( const_str_plain_s );
    const_tuple_str_plain_PDFObjectNotFound_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PDFObjectNotFound_tuple, 0, const_str_plain_PDFObjectNotFound ); Py_INCREF( const_str_plain_PDFObjectNotFound );
    const_tuple_str_plain_self_str_plain_fp_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_fp_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_fp_tuple, 1, const_str_plain_fp ); Py_INCREF( const_str_plain_fp );
    const_tuple_str_plain_self_str_plain_cid_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_cid_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_cid_tuple, 1, const_str_plain_cid ); Py_INCREF( const_str_plain_cid );
    const_tuple_str_plain_self_str_plain_ctm_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_ctm_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_ctm_tuple, 1, const_str_plain_ctm ); Py_INCREF( const_str_plain_ctm );
    const_tuple_str_plain_self_str_plain_obj_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_obj_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_obj_tuple, 1, const_str_plain_obj ); Py_INCREF( const_str_plain_obj );
    const_tuple_str_plain_self_str_plain_pos_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_pos_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_pos_tuple, 1, const_str_plain_pos ); Py_INCREF( const_str_plain_pos );
    const_tuple_str_plain_self_str_plain_tag_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_tag_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_tag_tuple, 1, const_str_plain_tag ); Py_INCREF( const_str_plain_tag );
    const_tuple_str_plain_self_str_plain_data_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_data_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_data_tuple, 1, const_str_plain_data ); Py_INCREF( const_str_plain_data );
    const_tuple_str_plain_self_str_plain_name_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_name_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_name_tuple, 1, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    const_tuple_str_plain_self_str_plain_objs_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_objs_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_objs_tuple, 1, const_str_plain_objs ); Py_INCREF( const_str_plain_objs );
    const_tuple_str_plain_self_str_plain_page_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_page_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_page_tuple, 1, const_str_plain_page ); Py_INCREF( const_str_plain_page );
    const_tuple_str_plain_self_str_plain_text_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_text_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_text_tuple, 1, const_str_plain_text ); Py_INCREF( const_str_plain_text );
    const_tuple_str_plain_PDFUnicodeNotDefined_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_PDFUnicodeNotDefined_tuple, 0, const_str_plain_PDFUnicodeNotDefined ); Py_INCREF( const_str_plain_PDFUnicodeNotDefined );
    const_str_digest_00b407740d742ef21d6f97842b0811ea = UNSTREAM_STRING( &constant_bin[ 200134 ], 8, 0 );
    const_str_digest_06b582bb8a7d7354812dca18aef147d5 = UNSTREAM_STRING( &constant_bin[ 176355 ], 20, 0 );
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING( &constant_bin[ 191288 ], 2, 0 );
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING( &constant_bin[ 175198 ], 7, 0 );
    const_str_digest_4b5c38a441de1271115ffc49566d0c91 = UNSTREAM_STRING( &constant_bin[ 175117 ], 15, 0 );
    const_str_digest_4d088de100fe5354b20a010ce1db7f29 = UNSTREAM_STRING( &constant_bin[ 165895 ], 14, 0 );
    const_str_digest_58961c73026e70b23b08cf381b49e04e = UNSTREAM_STRING( &constant_bin[ 200142 ], 15, 0 );
    const_str_digest_5bc6acbbb9e0adb8dabbc1a8cf202f2d = UNSTREAM_STRING( &constant_bin[ 189232 ], 16, 0 );
    const_str_digest_5cf0452130fc4fd9d925cac8f015f9d1 = UNSTREAM_STRING( &constant_bin[ 200157 ], 12, 0 );
    const_str_digest_6d86adbb5b668bab4cd670281ea4b3e0 = UNSTREAM_STRING( &constant_bin[ 200169 ], 4, 0 );
    const_str_digest_7532b9d7f11d8fedcf0f9e47d9f9d1da = UNSTREAM_STRING( &constant_bin[ 173993 ], 2, 0 );
    const_str_digest_7bb187c562694df4ba2daaaf74308c83 = UNSTREAM_STRING( &constant_bin[ 194565 ], 9, 0 );
    const_str_digest_89cffbfc3ef10076664cbfd1fe7e6033 = UNSTREAM_STRING( &constant_bin[ 187083 ], 18, 0 );
    const_str_digest_8e5335fb02f73f9b285b14387631d654 = UNSTREAM_STRING( &constant_bin[ 178912 ], 2, 0 );
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING( &constant_bin[ 200173 ], 46, 0 );
    const_str_digest_a5f56e291553139a63a10626179e7804 = UNSTREAM_STRING( &constant_bin[ 5534 ], 15, 0 );
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING( &constant_bin[ 200219 ], 47, 0 );
    const_str_digest_b3b014cceb34671e9d2eebc9b6361b5c = UNSTREAM_STRING( &constant_bin[ 7417 ], 18, 0 );
    const_str_digest_b9c4baf879ebd882d40843df3a4dead7 = UNSTREAM_STRING( &constant_bin[ 7866 ], 2, 1 );
    const_str_digest_c075052d723d6707083e869a0e3659bb = UNSTREAM_STRING( &constant_bin[ 200266 ], 5, 0 );
    const_str_digest_d1e9155136963092d9fab9b67fbb0f7f = UNSTREAM_STRING( &constant_bin[ 175832 ], 18, 0 );
    const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77 = UNSTREAM_STRING( &constant_bin[ 1463 ], 2, 0 );
    const_str_digest_e399ba4554180f37de594a6743234f17 = UNSTREAM_STRING( &constant_bin[ 200271 ], 7, 0 );
    const_str_digest_f454f8d0bf3383d8495a04e69ba795a3 = UNSTREAM_STRING( &constant_bin[ 200278 ], 32, 0 );
    const_str_digest_f6a581251841acee771bacb236f706e6 = UNSTREAM_STRING( &constant_bin[ 190942 ], 18, 0 );
    const_str_digest_fa91b370bf4aa8601b20ad022c04c7f5 = UNSTREAM_STRING( &constant_bin[ 175982 ], 14, 0 );
    const_tuple_9610428a1ba6846a8d44a05bfd7779c2_tuple = PyTuple_New( 4 );
    PyTuple_SET_ITEM( const_tuple_9610428a1ba6846a8d44a05bfd7779c2_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_9610428a1ba6846a8d44a05bfd7779c2_tuple, 1, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    PyTuple_SET_ITEM( const_tuple_9610428a1ba6846a8d44a05bfd7779c2_tuple, 2, const_str_plain_bbox ); Py_INCREF( const_str_plain_bbox );
    PyTuple_SET_ITEM( const_tuple_9610428a1ba6846a8d44a05bfd7779c2_tuple, 3, const_str_plain_matrix ); Py_INCREF( const_str_plain_matrix );
    const_tuple_b0c00933e83a0151953f3a00c2178204_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_b0c00933e83a0151953f3a00c2178204_tuple, 0, const_str_digest_b9c4baf879ebd882d40843df3a4dead7 ); Py_INCREF( const_str_digest_b9c4baf879ebd882d40843df3a4dead7 );
    PyTuple_SET_ITEM( const_tuple_b0c00933e83a0151953f3a00c2178204_tuple, 1, const_str_plain_k ); Py_INCREF( const_str_plain_k );
    PyTuple_SET_ITEM( const_tuple_b0c00933e83a0151953f3a00c2178204_tuple, 2, const_str_plain_v ); Py_INCREF( const_str_plain_v );
    const_tuple_str_digest_00b407740d742ef21d6f97842b0811ea_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_00b407740d742ef21d6f97842b0811ea_tuple, 0, const_str_digest_00b407740d742ef21d6f97842b0811ea ); Py_INCREF( const_str_digest_00b407740d742ef21d6f97842b0811ea );
    const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple, 0, const_str_digest_c075052d723d6707083e869a0e3659bb ); Py_INCREF( const_str_digest_c075052d723d6707083e869a0e3659bb );
    const_tuple_str_digest_fa91b370bf4aa8601b20ad022c04c7f5_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_fa91b370bf4aa8601b20ad022c04c7f5_tuple, 0, const_str_digest_fa91b370bf4aa8601b20ad022c04c7f5 ); Py_INCREF( const_str_digest_fa91b370bf4aa8601b20ad022c04c7f5 );
    const_tuple_str_plain_self_str_plain_objs_str_plain_obj_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_objs_str_plain_obj_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_objs_str_plain_obj_tuple, 1, const_str_plain_objs ); Py_INCREF( const_str_plain_objs );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_objs_str_plain_obj_tuple, 2, const_str_plain_obj ); Py_INCREF( const_str_plain_obj );
    const_tuple_str_plain_self_str_plain_tag_str_plain_props_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_tag_str_plain_props_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_tag_str_plain_props_tuple, 1, const_str_plain_tag ); Py_INCREF( const_str_plain_tag );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_tag_str_plain_props_tuple, 2, const_str_plain_props ); Py_INCREF( const_str_plain_props );
    const_tuple_str_plain_self_str_plain_name_str_plain_stream_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_name_str_plain_stream_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_name_str_plain_stream_tuple, 1, const_str_plain_name ); Py_INCREF( const_str_plain_name );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_name_str_plain_stream_tuple, 2, const_str_plain_stream ); Py_INCREF( const_str_plain_stream );
    const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_x_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_x_tuple, 0, const_str_digest_b9c4baf879ebd882d40843df3a4dead7 ); Py_INCREF( const_str_digest_b9c4baf879ebd882d40843df3a4dead7 );
    PyTuple_SET_ITEM( const_tuple_str_digest_b9c4baf879ebd882d40843df3a4dead7_str_plain_x_tuple, 1, const_str_plain_x ); Py_INCREF( const_str_plain_x );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_58961c73026e70b23b08cf381b49e04e
    );
#endif
}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
